### ISSUE TITLE
一直提示cannot find module ‘xxx’

### ISSUE THREAD

**Issue by windpursuer** [PromeYang/prome-sync#1]
已经完全按照步骤安装，初始化项目无法启动，一直报错，请指教

**Comment by PromeYang** [comment]
你的系统是不是windows的?如果是windows的话,请稍等一下,我会更新一个适用于windows的脚本,目前是适用于mac的,对你造成不便,不好意思,能期待一下我的更新吗?

**Comment by atlas-comstock** [comment]
@windpursuer 请贴出报错信息:)

**Comment by PromeYang** [comment]
这个工作流是基于 node 4.x npm 2.x的版本
