### ISSUE TITLE
请问小草版主

### ISSUE THREAD

**Issue by fangjj** [PromeYang/prome-sync#4]
这个项目还可以用吗？

**Comment by fangjj** [comment]
如何在apicloud坏境中如何使用?

**Comment by PromeYang** [comment]
这个项目还在使用, 按照教程安装使用,

**Comment by PromeYang** [comment]
这个工作流是基于 node 4.x npm 2.x的版本

**Comment by fangjj** [comment]
我按照教程按照，使用apicloud模板创建项目后，在新的终端执行 ./prome-sync， 输入ip: 192.168.2.128和端口3377，然后在海马玩模拟器上启动AppLoader， 输入刚才的ip和端口连接不上。
这是因为还需要下载apicloud开发工具APICloud Studio吗？目前我只下载了AppLoader，另外生成的apicloud模板缺少config.xml，目前还不明白这个工具如何配合apicloud开发。希望小草版主具体讲一下。
